package com.snwm.enums;

public enum Operator {
    A1("a1"),
    LYCAMOBILE("lycamobile"),
    ORANGE("orange"),
    TELERING("telering"),
    BULSATCOM("bulsatcom"),
    MAX_TELECOM("max telecom"),
    TELENOR("telenor"),
    VIVACOM("vivacom"),
    NORDIC_TELECOM("nordic telecom"),
    O2("o2"),
    SZDC("szdc"),
    TMOBILE("tmobile"),
    VODAFONE("vodafone"),
    ELISA("elisa"),
    TELE2("tele2"),
    TELIA("telia"),
    DNA("dna"),
    LEBARA("lebara"),
    SFR("sfr"),
    SYMAMOBILE("symamobile"),
    BEELINE("beeline"),
    GEOCELL("geocell"),
    MAGTICOM("magticom"),
    SILKNET("silknet"),
    COSMOTE("cosmote"),
    CYTA("cyta"),
    WIND("wind"),
    CHINA_MOBILE("china mobile"),
    CSL("csl"),
    PCCW("pccw"),
    SMARTONE("smartone"),
    THREE("three"),
    AXIS("axis"),
    INDOSAT("indosat"),
    SMARTFREN("smartfren"),
    TELKOMSEL("telkomsel"),
    ACTIV("activ"),
    ALTEL("altel"),
    FORTE_MOBILE("forte mobile"),
    AIRTEL("airtel"),
    ECONET("econet"),
    SAFARICOM("safaricom"),
    TELKOM("telkom"),
    ETL("etl"),
    LAOTEL("laotel"),
    UNITEL("unitel"),
    LMT("lmt"),
    CELCOM("celcom"),
    DIGI("digi"),
    ELECTCOMS("electcoms"),
    MAXIS("maxis"),
    TELEKOM("telekom"),
    TUNE_TALK("tune talk"),
    U_MOBILE("u mobile"),
    YES("yes"),
    TELCEL("telcel"),
    MOLDCELL("moldcell"),
    INWI("inwi"),
    MAROC_TELECOM("maroc telecom"),
    KPN("kpn"),
    LMOBIEL("lmobiel"),
    CHARJI("charji"),
    JAZZ("jazz"),
    SCO_MOBILE("sco mobile"),
    UFONE("ufone"),
    ZONG("zong"),
    GLOBE_TELECOM("globe telecom"),
    SMART("smart"),
    SUN_CELLULAR("sun cellular"),
    NJU("nju"),
    PYLDUK("pylduk"),
    PLAY("play"),
    PLUS("plus"),
    MEGAFON("megafon"),
    LABAS("labas"),
    MEGACOM("megacom"),
    O_PLUS("o!"),
    MTS("mts"),
    MTT("mtt"),
    PATRIOT("patriot"),
    ROSTELECOM("rostelecom"),
    TINKOFF("tinkoff"),
    VECTOR("vector"),
    VTB_MOBILE("vtbmobile"),
    YOTA("yota"),
    YOIGO("yoigo"),
    COMVIQ("comviq"),
    AIS("ais"),
    DTAC("dtac"),
    TRUEMOVE("truemove"),
    KYIVSTAR("kyivstar"),
    LIFECELL("lifecell"),
    EE("ee"),
    GIFFGAFF("giffgaff"),
    PERFECTUM("perfectum"),
    UCELL("ucell"),
    UMS("ums"),
    UZMOBILE("uzmobile"),
    VIETNAMOBILE("vietnamobile"),
    VIETTEL("viettel"),
    VINAPHONE("vinaphone"),
    NONE("");

    private final String code;

    Operator(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
